[font]
size = 7.5

normal = { family = "Cascadia Code", style = "Regular" }
bold = { family = "Cascadia Code", style = "Bold" }
italic = { family = "Cascadia Code", style = "Italic" }
bold_italic = { family = "Cascadia Code", style = "Bold Italic" }

[general]
import = [ "~/.config/alacritty/themes/themes/campbell.toml" ]


